export const POST_CUSTOMER_REQUEST = "POST_CUSTOMER_REQUEST";
export const POST_CUSTOMER_SUCCESS = "POST_CUSTOMER_SUCCESS";
export const POST_CUSTOMER_FAIL = "POST_CUSTOMER_FAIL";

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL";