export const POST_DEPARTMENT_REQUEST = "POST_DEPARTMENT_REQUEST";
export const POST_DEPARTMENT_SUCCESS = "POST_DEPARTMENT_SUCCESS";
export const POST_DEPARTMENT_FAIL = "POST_DEPARTMENT_FAIL";

export const POST_RANK_REQUEST = "POST_RANK_REQUEST";
export const POST_RANK_SUCCESS = "POST_RANK_SUCCESS";
export const POST_RANK_FAIL = "POST_RANK_FAIL";

export const POST_ROLE_REQUEST = "POST_ROLE_REQUEST";
export const POST_ROLE_SUCCESS = "POST_ROLE_SUCCESS";
export const POST_ROLE_FAIL = "POST_ROLE_FAIL";