export const LOGIN_STAFF_REQUEST = "LOGING_STAFF_REQUEST";
export const LOGIN_STAFF_SUCCESS = "LOGING_STAFF_SUCCESS";
export const LOGIN_STAFF_FAIL = "LOGING_STAFF_FAIL";

export const SIGNUP_STAFF_REQUEST = "SIGNUP_STAFF_REQUEST";
export const SIGNUP_STAFF_SUCCESS = "SIGNUP_STAFF_SUCCESS";
export const SIGNUP_STAFF_FAIL = "SIGNUP_STAFF_FAIL";