export const POST_STAFF_REQUEST = "POST_STAFF_REQUEST";
export const POST_STAFF_SUCCESS = "POST_STAFF_SUCCESS";
export const POST_STAFF_FAIL = "POST_STAFF_FAIL";

export const GET_STAFF_REQUEST = "GET_STAFF_REQUEST";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_FAIL = "GET_STAFF_FAIL";